name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu Kopyala
      uses: actions/checkout@v3

    - name: Java Kurulumu
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Flutter Kurulumu
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x'

    - name: Bağımlılıkları Yükle
      run: flutter pub get

    - name: APK Derle (Build)
      run: flutter build apk --release

    - name: APK Dosyasını Kaydet (Artifact)
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        
